apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 name: argocd-app
 namespace: argocd     
spec:
 project: default
 destination:
   name: in-cluster
   namespace: default
 source:
   chart: argo-cd
   repoURL: https://argoproj.github.io/argo-helm
   targetRevision: 7.3.2
   helm:
     releaseName: argo
 syncPolicy:
   automated:
     prune: false 
     selfHeal: true 
     allowEmpty: false 


